# Generated by Django 5.0 on 2024-11-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now=True)),
                ('phone', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(null=True)),
                ('group', models.ManyToManyField(related_name='group', to='apis.group')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('omadan', models.TimeField(blank=True, null=True)),
                ('raftan', models.TimeField(blank=True, null=True)),
                ('der_mekunam', models.TextField(blank=True, null=True)),
                ('nameoyam', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='apis.students')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
