# Generated by Django 5.0 on 2024-11-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='der_mekunam',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='nameoyam',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='omadan',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='raftan',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='apis.students'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
